// Frozen-compatible Runtime extracted from the source project. Main UI primitives remain separate.
import './vendor/runtime.css'
import '../design-system/primitives/Table/Table.css'
export * from './vendor/runtime.js'
// Explicit exports override the compatibility bundle for migrated components.
export { DSButton } from '../design-system/primitives/Button'
export type { DSButtonProps, ButtonVariant, LegacyButtonVariant, ButtonSemantic, ControlSize } from '../design-system/primitives/Button'
export { RUNTIME_COMPONENT_REGISTRY, listRuntimeComponents, getRuntimeComponent, isRuntimeComponentExport } from './registry'
export type { RuntimeComponentEntry } from './registry'
export { DSInput, DSTextArea } from '../design-system/primitives/TextField'
export type { DSInputProps, DSTextAreaProps, InputSize } from '../design-system/primitives/TextField'
export { DSCheckbox, DSSwitch, DSRadio, DSForm } from '../design-system/primitives/Forms'
export type { DSCheckboxProps, DSSwitchProps, DSRadioProps, DSFormProps } from '../design-system/primitives/Forms'

export { DSCheckboxGroup, DSField } from '../design-system/primitives/Forms'
export type { DSCheckboxGroupProps, DSFieldProps, DSFieldControlProps } from '../design-system/primitives/Forms'
export { DSTabs } from '../design-system/primitives/Navigation'
export type { DSTabsProps, DSTabItem } from '../design-system/primitives/Navigation'
export { DSDialog, DSDrawer } from '../design-system/primitives/Overlays'
export type { DSDialogProps, DSDrawerProps, DialogSize } from '../design-system/primitives/Overlays'
export { DSSelect } from '../design-system/primitives/Select'
export type { DSSelectProps, DSSelectOption, SelectSize } from '../design-system/primitives/Select'
export * from '../design-system/primitives/AdvancedFields'
export * from '../design-system/primitives/Collections'
export * from '../design-system/primitives/Content'
export * from '../design-system/primitives/DateTime'
export * from '../design-system/primitives/Colors'
export * from '../design-system/primitives/Collections/Additional'
export { DSAccordion as DSDisclosureGroup, DSSeparator as DSDivider } from '../design-system/primitives/Collections'
export { DSProgressBar as DSProgress } from '../design-system/primitives/AdvancedFields'
export { DSTimeField as DSTimePicker } from '../design-system/primitives/DateTime'
export { DSColorPicker } from '../design-system/primitives/Colors/ColorPicker'
export { DSIconAction } from '../design-system/primitives/IconAction'
export type { DSIconActionProps, DismissIconSemantic } from '../design-system/primitives/IconAction'
export * from '../design-system/primitives/Collections/Tree'
export { DSLoading, DSEmpty, DSAlert, DSTag, DSBadge, DSToast, DSMessage, DSSpinner, DSProgressCircle } from '../design-system/primitives/Feedback'
export type { DSLoadingProps, DSEmptyProps, DSAlertProps, DSTagProps, DSBadgeProps, DSToastProps, FeedbackTone, FeedbackSize } from '../design-system/primitives/Feedback'
export { DSUpload } from '../design-system/primitives/Upload'
export type { DSUploadProps } from '../design-system/primitives/Upload'
export { Button } from '../design-system/primitives/Button'

export { DSPagination } from '../design-system/primitives/Pagination'
export type { DSPaginationProps } from '../design-system/primitives/Pagination'

export { DSTable } from '../design-system/primitives/Table'
export type { DSTableProps, DSTableColumn } from '../design-system/primitives/Table'

export * from '../design-system/primitives/AI'
