import { MenuExample, TabsExample } from './NavigationExample'
import { AIExample } from './AIExample'
import { AI_COMPONENT_IDS } from '../data/ai-components'
import { TableSelectionBar } from './TableSelectionBar'
import { GroupedTableExample } from './GroupedTableExample'
import { parseDate, parseTime } from '@internationalized/date'
import { useMemo, useState } from 'react'
import * as DS from '../runtime'
import { DEMO_BRAND_SWATCHES, DEMO_COLORS, DEMO_HUE_COLORS, DEMO_STATUS_SWATCHES } from '../data/demo-colors'
// Stable sample data prevents the table from resetting its page on selection rerenders.
const resourceRows=[
  {id:'1',name:'设计规范',type:'规范',owner:'设计团队',status:'使用中'},
  {id:'2',name:'组件文档',type:'文档',owner:'前端团队',status:'使用中'},
  {id:'3',name:'验收记录',type:'记录',owner:'质量团队',status:'待处理'},
 ]
function FormExample({children,size='default'}:{children:React.ReactNode;size?:'compact'|'default'|'wide'}) { return <div className={`runtime-form-example runtime-form-example--${size}`}>{children}</div> }
export function RuntimeExample({id,demoVariant='default',disabled=false,buttonVariant='primary',buttonSemantic='default',buttonSize='md',buttonLoading=false,buttonBlock=false,tableDensity='default',tableSelectable=false}:{id:string;demoVariant?:string;disabled?:boolean;buttonVariant?:'primary'|'secondary'|'tertiary';buttonSemantic?:'default'|'danger';buttonSize?:'sm'|'md'|'lg';buttonLoading?:boolean;buttonBlock?:boolean;tableDensity?:'compact'|'default'|'comfortable';tableSelectable?:boolean}) {
 const [finishedLoading,setFinishedLoading]=useState(false); const [value,setValue]=useState(''); const [open,setOpen]=useState(false); const [page,setPage]=useState<number | null>(null); const [sort,setSort]=useState<{key:string;dir:'asc'|'desc'}|null>(null); const [selectedRows,setSelectedRows]=useState<string[]>([]); const [removedFiles,setRemovedFiles]=useState<string[]>([])
 const options=[{id:'design',label:'设计'},{id:'develop',label:'开发'},{id:'review',label:'审核',disabled:true}]
 const [rowStatuses,setRowStatuses]=useState<Record<string,string>>({})
 const rows=useMemo(()=>resourceRows.map(row=>({...row,status:rowStatuses[row.id]??row.status})),[rowStatuses])
 const is=(variant:string)=>demoVariant===variant
 const isDisabled=disabled||is('disabled')||demoVariant.endsWith('-disabled')
 const demoColor=is('green')?DEMO_COLORS.positive:is('red')?DEMO_COLORS.critical:DEMO_COLORS.brand
 const demoHueColor=is('green')?DEMO_HUE_COLORS.positive:is('red')?DEMO_HUE_COLORS.critical:DEMO_HUE_COLORS.brand
 const pickedDate=parseDate('2026-09-19')
 const dateProps={isDisabled,isReadOnly:is('readonly'),isInvalid:is('invalid'),minValue:is('bounded')?parseDate('2026-09-01'):undefined,maxValue:is('bounded')?parseDate('2026-09-30'):undefined,isDateUnavailable:is('unavailable')?(date:{day:number})=>date.day===20:undefined}
 const dateValue=is('selected')||is('readonly')||is('bounded')?pickedDate:undefined
 const timeProps={isDisabled,isReadOnly:is('readonly'),isInvalid:is('invalid'),defaultValue:is('selected')||is('readonly')?parseTime('14:30'):undefined,minValue:is('bounded')?parseTime('09:00'):undefined,maxValue:is('bounded')?parseTime('18:00'):undefined}
 const render=()=>{
 if(AI_COMPONENT_IDS.includes(id))return <AIExample id={id} variant={demoVariant}/>
 switch(id) {
 case 'button': return <div style={{width:'100%',display:'flex',justifyContent:'center'}}><DS.DSButton loading={buttonLoading} disabled={disabled || buttonLoading} aria-busy={buttonLoading || undefined} variant={buttonVariant} semantic={buttonSemantic} size={buttonSize} style={buttonBlock?{width:'100%'}:undefined} onClick={()=>setValue('操作已触发')}>{`确定${value ? ` · ${value}` : ''}`}</DS.DSButton></div>
 case 'input': return <FormExample><DS.DSInput label="项目名称" defaultValue={is('filled')||is('readonly')?'资源管理平台':''} readOnly={is('readonly')} required={is('required')} maxLength={is('max-length')?8:undefined} description={is('max-length')?'最多 8 个字符':undefined} prefix={is('adornments')?'https://':undefined} suffix={is('adornments')?'.com':undefined} onChange={setValue} placeholder="请输入项目名称" clearable disabled={isDisabled} invalid={is('invalid')} errorMessage={is('invalid')?'请输入有效的项目名称':undefined} /></FormExample>
 case 'button-group': return <DS.DSButtonGroup label="操作"><DS.DSButton variant="primary" disabled={isDisabled}>保存</DS.DSButton><DS.DSButton variant="secondary" disabled={isDisabled}>取消</DS.DSButton>{is('mixed')&&<DS.DSButton variant="tertiary" disabled={isDisabled}>预览</DS.DSButton>}</DS.DSButtonGroup>
 case 'close-button': return <><DS.DSCloseButton disabled={isDisabled} onPress={()=>setValue('已关闭')} /><p role="status">{value}</p></>
 case 'input-group': return <FormExample size="wide"><DS.DSInputGroup label={is('amount')?'金额':'链接'}><span>{is('amount')?'¥':'https://'}</span><input aria-label={is('amount')?'金额':'域名'} placeholder={is('amount')?'0.00':'example.com'} /></DS.DSInputGroup></FormExample>
 case 'input-otp': return <FormExample><DS.DSInputOTP label="验证码" length={is('four')?4:6} disabled={isDisabled} /></FormExample>
 case 'autocomplete': return <DS.DSAutocomplete label="搜索职责" options={is('no-results')?[]:options} defaultSelectedKey={is('selected')||is('readonly')?'design':undefined} isDisabled={isDisabled} isReadOnly={is('readonly')} isInvalid={is('invalid')} errorMessage={is('invalid')?'请选择有效职责':undefined} defaultInputValue={is('no-results')?'不存在的职责':undefined} />
 case 'cascader': return <DS.DSCascader label={is('department')?'部门':'地区'} options={is('department')?[{value:'product',label:'产品中心',children:[{value:'design',label:'设计组'},{value:'develop',label:'研发组'}]}]:[{value:'east',label:'华东',children:[{value:'sh',label:'上海'},{value:'hz',label:'杭州'}]},{value:'north',label:'华北',children:[{value:'bj',label:'北京'}]}]} />
 case 'textarea': return <FormExample size="wide"><DS.DSTextArea label="项目说明" defaultValue={is('filled')||is('readonly')?'用于统一项目组件与页面模板的视觉规范。':''} readOnly={is('readonly')} required={is('required')} maxLength={is('max-length')?30:undefined} description={is('max-length')?'最多 30 个字符':undefined} placeholder="请输入项目说明" disabled={isDisabled} invalid={is('invalid')} errorMessage={is('invalid')?'说明不能少于 10 个字':undefined} /></FormExample>
 case 'checkbox': return <DS.DSCheckbox label="接收通知" defaultChecked={is('checked')||is('checked-disabled')} indeterminate={is('indeterminate')||is('indeterminate-disabled')} loading={is('loading')} invalid={is('invalid')} errorMessage={is('invalid')?'请确认此选项':undefined} disabled={isDisabled} />
 case 'switch': return <DS.DSSwitch label="显示详细信息" defaultChecked={is('checked')||is('checked-disabled')} loading={is('loading')} disabled={isDisabled} />
 case 'checkbox-group': return <DS.DSCheckboxGroup label="权限" disabled={isDisabled} loading={is('loading')} defaultValue={is('selected')||is('selected-disabled')?['design','develop']:undefined} invalid={is('invalid')} errorMessage={is('invalid')?'请至少选择一项权限':undefined} options={options.map(x=>({...x,value:x.id}))} />
 case 'radio': return <DS.DSRadio label="职责" disabled={isDisabled} loading={is('loading')} invalid={is('invalid')} errorMessage={is('invalid')?'请选择职责':undefined} defaultValue={is('selected')||is('selected-disabled')?'design':undefined} options={options.map(x=>({...x,value:x.id}))} />
 case 'select': return <DS.DSSelect label="职责" disabled={isDisabled} readOnly={is('readonly')} required={is('required')} clearable={is('clearable')||is('readonly')||is('required')} defaultValue={['selected','readonly','required','clearable','long-option'].includes(demoVariant)?'design':undefined} invalid={is('invalid')} errorMessage={is('invalid')?'请选择职责':undefined} placeholder="请选择" options={is('empty')?[]:options.map(x=>({...x,value:x.id,label:is('long-option')?`${x.label}：跨部门资源协作与发布审批流程中的长选项名称`:x.label}))} />
 case 'combo-box': return <DS.DSComboBox label="搜索职责" options={is('no-results')?[]:options} defaultSelectedKey={is('selected')||is('readonly')?'design':undefined} isDisabled={isDisabled} isReadOnly={is('readonly')} isInvalid={is('invalid')} errorMessage={is('invalid')?'请选择有效职责':undefined} defaultInputValue={is('no-results')?'不存在的职责':undefined} />
 case 'color-area': return <DS.DSColorArea aria-label="颜色区域" defaultValue={demoColor} colorSpace="hsb" xChannel="saturation" yChannel="brightness" />
 case 'color-field': return <DS.DSColorField label="颜色值" defaultValue={demoColor} />
 case 'color-slider': return <DS.DSColorSlider label="色相" channel="hue" defaultValue={demoHueColor} />
 case 'color-swatch': return <DS.DSColorSwatch color={demoColor} />
 case 'color-swatch-picker': return <DS.DSColorSwatchPicker aria-label="选择颜色" colors={[...(is('status')?DEMO_STATUS_SWATCHES:DEMO_BRAND_SWATCHES)]} />
 case 'calendar': return <DS.DSCalendar aria-label="日历" {...dateProps} defaultValue={dateValue} defaultFocusedValue={pickedDate} />
 case 'range-calendar': return <DS.DSRangeCalendar aria-label="日期范围" {...dateProps} defaultValue={dateValue?{start:dateValue,end:dateValue.add({days:3})}:undefined} defaultFocusedValue={pickedDate} />
 case 'date-field': return <DS.DSDateField label="日期" {...dateProps} defaultValue={dateValue} />
 case 'date-picker': return <DS.DSDatePicker label="日期" {...dateProps} defaultValue={dateValue} />
 case 'date-range-picker': return <DS.DSDateRangePicker label="日期范围" {...dateProps} defaultValue={dateValue?{start:dateValue,end:dateValue.add({days:3})}:undefined} />
 case 'time-picker': return <DS.DSTimePicker label="时间" {...timeProps} />
 case 'color-picker': return <DS.DSColorPicker label="选择颜色" defaultValue={demoColor} />
 case 'time-field': return <DS.DSTimeField label="时间" {...timeProps} />
 case 'number-field': return <FormExample size="compact"><DS.DSNumberField label="数量" defaultValue={is('min')?0:is('max')?10:2} minValue={0} maxValue={10} isDisabled={isDisabled} isReadOnly={is('readonly')} isInvalid={is('invalid')} errorMessage={is('invalid')?'数量无效':undefined} /></FormExample>
 case 'search-field': return <DS.DSSearchField label="搜索资源" defaultValue={is('filled')||is('readonly')?'按钮':undefined} isDisabled={isDisabled} isReadOnly={is('readonly')} isInvalid={is('invalid')} errorMessage={is('invalid')?'请检查搜索条件':undefined} />
 case 'slider': return <DS.DSSlider label={is('range')?'价格范围':'密度'} defaultValue={is('range')?[25,75]:40} isDisabled={isDisabled} />
 case 'progress': return <DS.DSProgress label="进度" value={is('complete')?100:40} />
 case 'progress-circle': return <DS.DSProgressCircle label="进度" value={is('complete')?100:65} />
 case 'spinner': return <DS.DSSpinner label="加载中" size={is('sm')?'sm':is('lg')?'lg':'md'} />
 case 'progress-bar': return <DS.DSProgressBar label="导入进度" value={is('complete')?100:65} />
 case 'meter': return <DS.DSMeter label="已用容量" value={is('critical')?95:is('warning')?75:35} />
 case 'tabs': return <TabsExample key={demoVariant} variant={demoVariant} disabled={isDisabled} />
 case 'alert-dialog': case 'modal': { const Overlay=id==='modal'?DS.DSModal:DS.DSAlertDialog;const danger=is('danger');const info=id==='modal'&&is('info');const title=danger?'确认删除资源':info?'版本说明':'确认提交';const finish=()=>{setValue(danger?'资源已删除':info?'已关闭说明':'操作已确认');setOpen(false)};return <div className="runtime-overlay-example"><DS.DSButton semantic={danger?'danger':'default'} onClick={()=>setOpen(true)}>{danger?'删除资源':info?'查看说明':'确认操作'}</DS.DSButton><Overlay open={open} onOpenChange={setOpen} title={title} description={danger?'此操作不可撤销，请确认后继续。':info?'查看当前组件的使用范围与限制。':'提交后将应用当前设置。'} footer={<><DS.DSButton variant="secondary" onClick={()=>setOpen(false)}>取消</DS.DSButton><DS.DSButton variant="primary" semantic={danger?'danger':'default'} onClick={finish}>{danger?'删除':info?'知道了':'确认'}</DS.DSButton></>}>{danger?<div className="runtime-overlay-warning"><DS.DSIcon name="warning" weight="filled" size="sm" decorative />删除后相关引用将无法继续使用。</div>:<dl className="runtime-overlay-details"><div><dt>适用范围</dt><dd>当前示例</dd></div><div><dt>操作结果</dt><dd>{info?'仅关闭说明，不修改数据':'保存当前设置'}</dd></div></dl>}</Overlay>{value&&<p className="runtime-overlay-feedback" role="status">{value}</p>}</div> }
 case 'dialog': case 'drawer': { const Overlay=id==='dialog'?DS.DSDialog:DS.DSDrawer; const form=is('form')||is('nested');const finish=()=>{setValue(form?'资源已保存':'详情已关闭');setOpen(false)};return <div className="runtime-overlay-example"><DS.DSButton onClick={()=>{setFinishedLoading(false);setOpen(true)}} disabled={isDisabled}>{form?'编辑资源':'查看详情'}</DS.DSButton><Overlay open={open} onOpenChange={setOpen} title={form?'编辑资源':'资源详情'} dismissible={!is('protected')} closeOnEscape={!is('protected')} loading={is('loading')&&!finishedLoading} description={form?'修改资源名称后保存。':'查看资源的基础信息。'} footer={<><DS.DSButton variant="secondary" disabled={is('loading')&&!finishedLoading} onClick={()=>setOpen(false)}>取消</DS.DSButton><DS.DSButton variant="primary" disabled={is('loading')&&!finishedLoading} onClick={finish}>{form?'保存':'完成'}</DS.DSButton></>}>{is('loading')&&!finishedLoading?<><DS.DSLoading label="正在读取资源"/><DS.DSButton variant="secondary" onClick={()=>setFinishedLoading(true)}>结束加载演示</DS.DSButton></>:is('long')?<div>{Array.from({length:20},(_,index)=><p key={index}>资源说明 {index+1}：此内容用于验证对话框或抽屉在长文案下独立滚动，页头与操作按钮始终可达。</p>)}</div>:is('protected')?<p>外部点击和 Escape 不关闭此浮层；可通过关闭图标或底部操作离开。</p>:form?<><DS.DSInput label="资源名称" defaultValue="示例资源" />{is('nested')&&<DS.DSSelect label="资源类型" options={options.map(x=>({...x,value:x.id}))}/>}</>:<dl className="runtime-overlay-details"><div><dt>资源名称</dt><dd>示例资源</dd></div><div><dt>资源类型</dt><dd>组件规范</dd></div><div><dt>更新时间</dt><dd>今天</dd></div></dl>}</Overlay>{value&&<p className="runtime-overlay-feedback" role="status">{value}</p>}</div> }
 case 'toast': return <><DS.DSButton onClick={()=>setOpen(true)} disabled={isDisabled}>显示通知</DS.DSButton><DS.DSToast open={open} onOpenChange={setOpen} tone={is('success')?'success':is('error')?'error':'info'} duration={is('restart')?1000:is('persistent')?0:5000} message={is('success')?'保存成功':is('error')?'保存失败，请稍后重试':'配置已更新'} /></>
 case 'alert': return <DS.DSAlert title={is('error')?'操作失败':is('success')?'保存成功':is('warning')?'请核对输入':'操作说明'} tone={is('error')?'error':is('success')?'success':is('warning')?'warning':'info'}>{is('error')?'请检查输入后重试。':is('success')?'更改已保存。':is('warning')?'部分内容需要确认。':'确认当前配置后继续。'}</DS.DSAlert>
 case 'empty': return value?<div><DS.DSCard title="示例资源">已创建一条本地示例。</DS.DSCard><DS.DSButton variant="secondary" onClick={()=>setValue('')}>重置为空状态</DS.DSButton></div>:<DS.DSEmpty title="暂无资源" description="添加资源后在此展示。" action={is('action')?<DS.DSButton onClick={()=>setValue('已创建示例')}>新增资源</DS.DSButton>:undefined} />
 case 'loading': return <DS.DSLoading label="正在加载" size={is('sm')?'sm':is('lg')?'lg':'md'} />
 case 'tag': return <div>{value!=='已移除标签'?<DS.DSTag onRemove={is('removable')||is('disabled')?()=>setValue('已移除标签'):undefined} disabled={isDisabled} label="设计">设计</DS.DSTag>:<DS.DSButton variant="secondary" onClick={()=>setValue('')}>恢复标签</DS.DSButton>}{value&&<p role="status">{value}</p>}</div>
 case 'badge': return <DS.DSBadge tone={is('success')?'success':is('warning')?'warning':is('error')?'error':'info'}>{is('success')?'成功':is('warning')?'警告':is('error')?'错误':'信息'}</DS.DSBadge>
 case 'table': { if(demoVariant.startsWith('grouped-')) return <GroupedTableExample fixed={is('grouped-fixed')||is('grouped-selection')} selectable={is('grouped-selection')} state={is('grouped-empty')?'empty':is('grouped-loading')?'loading':'ready'}/>;const paged=is('pagination')||is('paged-selection'); const density=is('compact')?'compact':is('comfortable')?'comfortable':tableDensity;const selectable=is('selection')||is('paged-selection')||tableSelectable;const data=is('empty')||is('no-results')?[]:sort?[...rows].sort((a,b)=>(sort.dir==='asc'?1:-1)*a.name.localeCompare(b.name,'zh-CN')):rows;const visibleIds=paged?data.slice((page??1)-1,page??1).map(row=>row.id):data.map(row=>row.id);const update=(status:string)=>{setRowStatuses(previous=>({...previous,...Object.fromEntries(selectedRows.map(id=>[id,status]))}));setValue(`已更新 ${selectedRows.length} 项`)};return <div className="runtime-selectable-table">{selectable&&<TableSelectionBar label="表格批量操作" count={selectedRows.length} otherPageCount={selectedRows.filter(id=>!visibleIds.includes(id)).length} onClear={()=>setSelectedRows([])} disabled={is('loading')}><DS.DSButton size="sm" variant="tertiary" disabled={is('loading')||isDisabled} onClick={()=>update('使用中')}>批量启用</DS.DSButton><DS.DSButton size="sm" variant="tertiary" disabled={is('loading')||isDisabled} onClick={()=>update('已停用')}>批量停用</DS.DSButton></TableSelectionBar>}<DS.DSTable variant={is('secondary')?'secondary':'primary'} footer={paged?<><DS.DSPagination total={rows.length} pageSize={1} pageSizeOptions={[1]} page={page??1} onPageChange={setPage}/></>:undefined} className="runtime-table-demo" columns={[{key:'name',title:'资源名称',width:180,sortable:is('sorting')},{key:'type',title:'类型',width:90},{key:'owner',title:'负责人',width:110},{key:'status',title:'状态',width:90,render:row=><span className={row.status==='待处理'?'runtime-table-status runtime-table-status--warning':'runtime-table-status'}>{row.status}</span>},{key:'actions',title:'操作',width:140,ellipsis:false,render:row=><span className="ds-table-actions" onClick={event=>event.stopPropagation()}><DS.DSButton className="runtime-table-action" variant="tertiary" size="sm" onClick={()=>setValue(`查看 ${row.name}`)}>查看</DS.DSButton><DS.DSButton className="runtime-table-action" variant="tertiary" size="sm" onClick={()=>setValue(`编辑 ${row.name}`)}>编辑</DS.DSButton></span>}]} data={data} loading={is('loading')} emptyState={is('no-results')?'没有符合搜索条件的资源':'暂无资源'} sort={sort} onSortChange={setSort} pagination={paged?{page:page??1,pageSize:1,onPageChange:setPage}:undefined} rowKey={row=>row.id} density={density} selectable={selectable} selectedRowKeys={selectedRows} onSelectionChange={setSelectedRows} /></div> }
 case 'pagination': { const current=page??(is('middle')?2:is('end')?3:1);return <><p>{rows[current-1].name}</p><DS.DSPagination disabled={isDisabled} total={3} pageSize={1} pageSizeOptions={[1]} page={current} onPageChange={setPage} /></> }
 case 'form': return <DS.DSForm label="示例表单" loading={is('loading')} disabled={isDisabled} error={is('error')?'保存失败，请检查字段后重试':undefined} success={value} onSubmit={()=>setValue('校验成功')}><DS.DSInput label="名称" name="name" required /><DS.DSButton type="submit">验证表单</DS.DSButton></DS.DSForm>
 case 'field': return <FormExample><DS.DSField label="名称" required={is('required')||is('error')} error={is('error')?'请输入名称':undefined}>{props=><input {...props} disabled={isDisabled} placeholder="请输入名称" required={is('required')||is('error')} />}</DS.DSField></FormExample>
 case 'upload': return <FormExample><div className="runtime-upload-example"><DS.DSUpload label="文件" loading={is('loading')} maxBytes={is('size-limit')?1024:undefined} multiple={is('multiple')} disabled={isDisabled} error={is('error')?'文件格式不支持，请重新选择':undefined} onFiles={files=>setValue(files.map(f=>f.name).join('、'))} />{is('size-limit')&&<p>每个文件不超过 1 KB；校验失败后可重新选择。</p>}{value&&<p role="status"><DS.DSIcon name="success" weight="filled" size="sm" decorative />已选择 {value}</p>}</div></FormExample>
 case 'accordion': return <DS.DSAccordion allowsMultipleExpanded={is('multiple')} items={[{id:'a',title:'使用说明',content:'可使用键盘展开和收起。'},{id:'b',title:'设计规则',content:'遵循项目变量绑定。'}]} />
 case 'breadcrumb': return <DS.DSBreadcrumb items={is('deep')?[{id:'a',label:'项目',href:'/projects'},{id:'b',label:'设计规范',href:'/assets'},{id:'c',label:'组件',href:'/components'},{id:'d',label:'当前示例'}]:[{id:'a',label:'组件',href:'/components'},{id:'b',label:'当前示例'}]} />
 case 'list-box': return <DS.DSListBox label="资源" items={options} selectionMode={is('multiple')?'multiple':'single'} />
 case 'tree': return <DS.DSTree label="资源树" selectionMode={is('multiple')?'multiple':'single'} items={[{id:'a',label:'设计规范',children:[{id:'a1',label:'颜色'},{id:'a2',label:'字体'}]}]} />
 case 'menu': return <MenuExample key={demoVariant} variant={demoVariant} disabled={isDisabled} />
 case 'disclosure': return <DS.DSDisclosure title="展开说明" disabled={isDisabled}>这是说明内容。</DS.DSDisclosure>
 case 'disclosure-group': return <DS.DSDisclosureGroup allowsMultipleExpanded={is('multiple')} items={[{id:'a',title:'说明',content:'内容'},{id:'b',title:'规则',content:'规则说明'}]} />
 case 'tag-group': return <div><DS.DSTagGroup label="标签" items={options.filter(item=>!removedFiles.includes(item.id))} onRemove={is('removable')?ids=>{setRemovedFiles(items=>[...items,...ids]);setValue('已移除标签')}:undefined}/>{removedFiles.length>0&&<DS.DSButton variant="secondary" onClick={()=>{setRemovedFiles([]);setValue('')}}>恢复标签</DS.DSButton>}{value&&<p role="status">{value}</p>}</div>
 case 'tooltip': { const placements:Record<string,'top'|'bottom'|'left'|'right'|'top start'|'top end'|'bottom start'|'bottom end'>={top:'top',bottom:'bottom',left:'left',right:'right','top-start':'top start','top-end':'top end','bottom-start':'bottom start','bottom-end':'bottom end'};const labels:Record<string,string>={top:'上方',bottom:'下方',left:'左侧',right:'右侧','top-start':'左上','top-end':'右上','bottom-start':'左下','bottom-end':'右下'};const placement=placements[demoVariant]??'top';return <DS.DSTooltip label={`${labels[demoVariant]??'上方'}提示内容`} placement={placement} offset={8} shouldFlip={false}>悬停或聚焦</DS.DSTooltip> }
 case 'popover': return <DS.DSPopover label="展开详情">{is('detailed')?'这里包含资源来源、更新时间和使用建议。':'这是详情内容。'}</DS.DSPopover>
 case 'popconfirm': return <div className="runtime-overlay-example"><DS.DSPopconfirm label={is('danger')?'删除资源':'确认操作'} tone={is('danger')?'danger':'default'} description={is('danger')?'删除后无法恢复，是否继续？':'是否应用当前设置？'} onConfirm={()=>setValue(is('danger')?'资源已删除':'操作已确认')}/>{value&&<p className="runtime-overlay-feedback" role="status">{value}</p>}</div>
 case 'message': return <DS.DSMessage title={is('error')?'操作失败':is('success')?'操作成功':is('warning')?'需要注意':'操作说明'} tone={is('error')?'error':is('success')?'success':is('warning')?'warning':'info'}>{is('error')?'请检查输入后重试。':is('success')?'更改已保存。':is('warning')?'部分内容需要确认。':'系统将在保存后应用当前配置。'}</DS.DSMessage>
 case 'steps': return <DS.DSSteps items={['填写','确认','完成']} current={is('start')?0:is('complete')?2:1} />
 case 'drop-zone': return <div className={`runtime-drop-zone-example${is('compact')?' runtime-drop-zone-example--compact':''}`}><DS.DSDropZone label={is('compact')?'拖入单个文件':'上传文件'} onFiles={files=>setValue(files.map(f=>f.name).join('、'))}/>{value&&<p role="status"><DS.DSIcon name="success" weight="filled" size="sm" decorative />已选择 {value}</p>}</div>
 case 'resizable-panel': return <DS.DSResizablePanel min={is('wide')?320:180} max={is('wide')?720:480}>调整宽度查看内容</DS.DSResizablePanel>
 case 'image-preview': { const square=is('square');return <DS.DSImagePreview src="/assets/hj-logo-112.png" aspect={square?'square':'landscape'} alt={square?'方形品牌标识':'横向品牌标识预览'} /> }
 case 'icon': return <div className="runtime-icon-grid">{[
   ['add','添加'],['edit','编辑'],['delete','删除'],['search','搜索'],['filter','筛选'],['calendar','日历'],
   ['user','用户'],['settings','设置'],['success','成功'],['warning','警告'],['upload','上传'],['download','下载'],
 ].map(([name,label])=><span key={name}><DS.DSIcon name={name} size={is('sm')?'sm':is('lg')?'lg':'md'} label={label} /><small>{label}</small></span>)}</div>
 case 'divider': { const vertical=is('vertical');return <div className={`runtime-separator-example${vertical?' runtime-separator-example--vertical':''}`}><span>{vertical?'左侧内容':'上方内容'}</span><DS.DSDivider orientation={vertical?'vertical':'horizontal'} /><span>{vertical?'右侧内容':'下方内容'}</span></div> }
 case 'dropdown': return <div className="runtime-menu-example"><DS.DSDropdown label="资源操作" items={is('disabled-item')?options:options.map(item=>({...item,disabled:false}))} onAction={key=>setValue(options.find(item=>item.id===key)?.label??key)} />{value&&<p role="status">已选择 {value}</p>}</div>
 case 'toggle-button': return <DS.DSToggleButton defaultSelected={is('selected')} isDisabled={isDisabled}>切换强调</DS.DSToggleButton>
 case 'toggle-button-group': return <DS.DSToggleButtonGroup selectionMode={is('multiple')?'multiple':'single'}><DS.DSToggleButton id="a">左对齐</DS.DSToggleButton><DS.DSToggleButton id="b">居中</DS.DSToggleButton></DS.DSToggleButtonGroup>
 case 'toolbar': return is('align')?<DS.DSToolbar aria-label="对齐"><DS.DSToggleButton>左对齐</DS.DSToggleButton><DS.DSToggleButton>居中</DS.DSToggleButton><DS.DSToggleButton>右对齐</DS.DSToggleButton></DS.DSToolbar>:<DS.DSToolbar aria-label="格式"><DS.DSToggleButton>强调</DS.DSToggleButton><DS.DSToggleButton>下划线</DS.DSToggleButton></DS.DSToolbar>
 case 'separator': { const vertical=is('vertical');return <div className={`runtime-separator-example${vertical?' runtime-separator-example--vertical':''}`}><span>{vertical?'左侧内容':'上方内容'}</span><DS.DSSeparator orientation={vertical?'vertical':'horizontal'} /><span>{vertical?'右侧内容':'下方内容'}</span></div> }
 case 'link': return <DS.DSLink href={is('external')?'https://react-spectrum.adobe.com/react-aria/':'/quick-start'} target={is('external')?'_blank':undefined}>快速开始{is('external')?'（外部）':''}</DS.DSLink>
 case 'card': return <DS.DSCard title="资源信息">{is('detailed')?<><p>组件与规范的集合。</p><DS.DSButton variant="secondary">查看详情</DS.DSButton></>:'组件与规范的集合。'}</DS.DSCard>
 case 'surface': return <DS.DSSurface style={is('subtle')?{background:'var(--surface-subtle)',padding:16}:undefined}>内容表面</DS.DSSurface>
 case 'stack': return <DS.DSStack direction={is('horizontal')?'row':'column'} align="flex-start"><DS.DSBadge>设计</DS.DSBadge><DS.DSBadge>开发</DS.DSBadge></DS.DSStack>
 case 'space': return <DS.DSStack direction="row" gap={is('loose')?'32px':'8px'} align="flex-start"><DS.DSBadge>设计</DS.DSBadge><DS.DSBadge>开发</DS.DSBadge></DS.DSStack>
 case 'grid': return <DS.DSGrid columns={is('three')?3:2}><DS.DSCard>设计</DS.DSCard><DS.DSCard>开发</DS.DSCard>{is('three')&&<DS.DSCard>测试</DS.DSCard>}</DS.DSGrid>
 case 'page-container': return <DS.DSPageContainer style={is('compact')?{padding:12,maxWidth:520}:undefined}>页面内容</DS.DSPageContainer>
 case 'kbd': return <DS.DSKbd>{is('search')?'Ctrl + K':'Ctrl + C'}</DS.DSKbd>
 case 'avatar': return <div><DS.DSAvatar name="设计师" src={is('recovery')?value||'/audit-intentionally-missing-avatar.png':is('image')?'/assets/hj-logo-112.png':undefined} size={is('sm')?24:is('lg')?48:32} />{is('recovery')&&<DS.DSButton variant="secondary" onClick={()=>setValue('/assets/hj-logo-112.png')}>替换有效图片</DS.DSButton>}</div>
 case 'descriptions': return <DS.DSDescriptions label="项目信息" items={is('detailed')?[{label:'项目',value:'演示项目'},{label:'状态',value:'草稿'},{label:'负责人',value:'设计团队'},{label:'更新时间',value:'今天'}]:[{label:'项目',value:'演示项目'},{label:'状态',value:'草稿'}]} />
 case 'file-list': { const files=[{id:'a',name:'说明.txt',size:256},{id:'b',name:'变量.json',size:1024}].filter(file=>!removedFiles.includes(file.id));return <div className="runtime-file-list-example">{files.length?<DS.DSFileList files={files} onRemove={is('removable')?fileId=>{setRemovedFiles(items=>[...items,fileId]);setValue(`已移除 ${fileId==='a'?'说明.txt':'变量.json'}`)}:undefined}/>:<DS.DSEmpty title="文件已全部移除" description="刷新页面可恢复示例文件。" />}{value&&<p role="status">{value}</p>}</div> }
 case 'skeleton': return <DS.DSSkeleton style={is('card')?{width:280,height:128}:{width:280,height:18}} />
 case 'scroll-shadow': return <DS.DSScrollShadow style={{maxHeight:is('tall')?260:120}}><p>滚动区域示例</p>{Array.from({length:20},(_,i)=><p key={i}>第 {i+1} 行</p>)}</DS.DSScrollShadow>
 default: return <p>尚未提供独立交互示例，不能据此认定该组件已完成验收。</p>
 }
 }
 return <div className={`runtime-example runtime-example--${id}`}>{render()}</div>
}
