// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/chat-source',component:RuntimeExample,tags:['autodocs'],args:{id:'chat-source',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","document","grouped","long"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"网页来源",args:{demoVariant:"default"} }
export const Document: Story = { name:"文档来源",args:{demoVariant:"document"} }
export const Grouped: Story = { name:"折叠来源",args:{demoVariant:"grouped"} }
export const Long: Story = { name:"长标题",args:{demoVariant:"long"} }
