// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/chat-list-view',component:RuntimeExample,tags:['autodocs'],args:{id:'chat-list-view',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","compact","empty","disabled"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"标准",args:{demoVariant:"default"} }
export const Compact: Story = { name:"紧凑",args:{demoVariant:"compact"} }
export const Empty: Story = { name:"空列表",args:{demoVariant:"empty"} }
export const Disabled: Story = { name:"禁用项",args:{demoVariant:"disabled"} }
