// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/chat-message',component:RuntimeExample,tags:['autodocs'],args:{id:'chat-message',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","user","streaming","error","stopped","rich"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"助手消息",args:{demoVariant:"default"} }
export const User: Story = { name:"用户消息",args:{demoVariant:"user"} }
export const Streaming: Story = { name:"生成中",args:{demoVariant:"streaming"} }
export const Error: Story = { name:"生成失败",args:{demoVariant:"error"} }
export const Stopped: Story = { name:"已停止",args:{demoVariant:"stopped"} }
export const Rich: Story = { name:"内容与来源",args:{demoVariant:"rich"} }
