// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/chain-of-thought',component:RuntimeExample,tags:['autodocs'],args:{id:'chain-of-thought',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","collapsed","streaming","nested","error"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"已完成",args:{demoVariant:"default"} }
export const Collapsed: Story = { name:"折叠",args:{demoVariant:"collapsed"} }
export const Streaming: Story = { name:"执行中",args:{demoVariant:"streaming"} }
export const Nested: Story = { name:"嵌套步骤",args:{demoVariant:"nested"} }
export const Error: Story = { name:"失败",args:{demoVariant:"error"} }
