// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/chat-tool',component:RuntimeExample,tags:['autodocs'],args:{id:'chat-tool',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","running","error","approval","rejected"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"执行结果",args:{demoVariant:"default"} }
export const Running: Story = { name:"执行中",args:{demoVariant:"running"} }
export const Error: Story = { name:"执行失败",args:{demoVariant:"error"} }
export const Approval: Story = { name:"等待确认",args:{demoVariant:"approval"} }
export const Rejected: Story = { name:"已拒绝",args:{demoVariant:"rejected"} }
