// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/code-block',component:RuntimeExample,tags:['autodocs'],args:{id:'code-block',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","json","plain","long"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"TypeScript",args:{demoVariant:"default"} }
export const Json: Story = { name:"JSON",args:{demoVariant:"json"} }
export const Plain: Story = { name:"纯文本",args:{demoVariant:"plain"} }
export const Long: Story = { name:"长代码",args:{demoVariant:"long"} }
