// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/chat-loader',component:RuntimeExample,tags:['autodocs'],args:{id:'chat-loader',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","pulse","spinner","skeleton"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"圆点",args:{demoVariant:"default"} }
export const Pulse: Story = { name:"脉冲",args:{demoVariant:"pulse"} }
export const Spinner: Story = { name:"旋转",args:{demoVariant:"spinner"} }
export const Skeleton: Story = { name:"骨架",args:{demoVariant:"skeleton"} }
