// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/chat-attachment',component:RuntimeExample,tags:['autodocs'],args:{id:'chat-attachment',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","uploading","error","removable","long"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"文件",args:{demoVariant:"default"} }
export const Uploading: Story = { name:"上传中",args:{demoVariant:"uploading"} }
export const Error: Story = { name:"失败重试",args:{demoVariant:"error"} }
export const Removable: Story = { name:"可移除",args:{demoVariant:"removable"} }
export const Long: Story = { name:"长文件名",args:{demoVariant:"long"} }
