// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/chat-conversation',component:RuntimeExample,tags:['autodocs'],args:{id:'chat-conversation',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","full-chat","streaming","empty","long"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"对话记录",args:{demoVariant:"default"} }
export const FullChat: Story = { name:"完整聊天",args:{demoVariant:"full-chat"} }
export const Streaming: Story = { name:"生成中",args:{demoVariant:"streaming"} }
export const Empty: Story = { name:"空会话",args:{demoVariant:"empty"} }
export const Long: Story = { name:"历史消息",args:{demoVariant:"long"} }
