// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/markdown',component:RuntimeExample,tags:['autodocs'],args:{id:'markdown',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","table","streaming","unsafe"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"富文本",args:{demoVariant:"default"} }
export const Table: Story = { name:"表格",args:{demoVariant:"table"} }
export const Streaming: Story = { name:"未完成内容",args:{demoVariant:"streaming"} }
export const Unsafe: Story = { name:"原始 HTML 不执行",args:{demoVariant:"unsafe"} }
