// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/prompt-input',component:RuntimeExample,tags:['autodocs'],args:{id:'prompt-input',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","inline","compact","attachments","streaming","error","disabled"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"标准",args:{demoVariant:"default"} }
export const Inline: Story = { name:"行内",args:{demoVariant:"inline"} }
export const Compact: Story = { name:"紧凑",args:{demoVariant:"compact"} }
export const Attachments: Story = { name:"含附件",args:{demoVariant:"attachments"} }
export const Streaming: Story = { name:"生成与停止",args:{demoVariant:"streaming"} }
export const Error: Story = { name:"发送失败",args:{demoVariant:"error"} }
export const Disabled: Story = { name:"禁用",args:{demoVariant:"disabled"} }
