// Generated by scripts/generate-ai-stories.ts.
import type {Meta,StoryObj} from '@storybook/react-vite'
import {RuntimeExample} from '../../components/RuntimeExample'
import {PreviewScope} from '../theme/PreviewScope'
import {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'
import '../../styles/index.css'
const meta={title:'AI/text-shimmer',component:RuntimeExample,tags:['autodocs'],args:{id:'text-shimmer',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","inactive"]}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>
export default meta
type Story=StoryObj<typeof meta>
export const Default: Story = { name:"生成中",args:{demoVariant:"default"} }
export const Inactive: Story = { name:"静态文字",args:{demoVariant:"inactive"} }
