// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.
import type { Meta, StoryObj } from '@storybook/react-vite'
import { RuntimeExample } from '../../components/RuntimeExample'
import { PreviewScope } from '../theme/PreviewScope'
import { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'
import { guokexinProject } from '../../data/projects/guokexin'
import '../../styles/index.css'
const meta = { title: 'Core/button', component: RuntimeExample, tags:['autodocs'], args:{id:'button',demoVariant:'primary'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["primary","secondary","tertiary","danger"]}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:"按钮：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。"}}} } satisfies Meta<typeof RuntimeExample>
export default meta
type Story = StoryObj<typeof meta>
export const Primary: Story = { name: "主要", args: { demoVariant: "primary", buttonVariant: "primary", buttonSemantic: "default" } }
export const Secondary: Story = { name: "次要", args: { demoVariant: "secondary", buttonVariant: "secondary", buttonSemantic: "default" } }
export const Tertiary: Story = { name: "文字", args: { demoVariant: "tertiary", buttonVariant: "tertiary", buttonSemantic: "default" } }
export const Danger: Story = { name: "危险", args: { demoVariant: "danger", buttonVariant: "primary", buttonSemantic: "danger" } }
export const Disabled: Story = {name:'禁用',args:{disabled:true}}
export const Loading: Story = {name:'加载',args:{buttonLoading:true}}
