// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.
import type { Meta, StoryObj } from '@storybook/react-vite'
import { RuntimeExample } from '../../components/RuntimeExample'
import { PreviewScope } from '../theme/PreviewScope'
import { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'
import { guokexinProject } from '../../data/projects/guokexin'
import '../../styles/index.css'
const meta = { title: 'Core/checkbox', component: RuntimeExample, tags:['autodocs'], args:{id:'checkbox',demoVariant:'default'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","checked","indeterminate","disabled","invalid","loading","checked-disabled","indeterminate-disabled"]}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:"复选框：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。"}}} } satisfies Meta<typeof RuntimeExample>
export default meta
type Story = StoryObj<typeof meta>
export const Default: Story = { name: "未选中", args: { demoVariant: "default" } }
export const Checked: Story = { name: "已选中", args: { demoVariant: "checked" } }
export const Indeterminate: Story = { name: "部分选中", args: { demoVariant: "indeterminate" } }
export const Disabled: Story = { name: "禁用", args: { demoVariant: "disabled" } }
export const Invalid: Story = { name: "错误", args: { demoVariant: "invalid" } }
export const Loading: Story = { name: "加载", args: { demoVariant: "loading" } }
export const CheckedDisabled: Story = { name: "选中且禁用", args: { demoVariant: "checked-disabled" } }
export const IndeterminateDisabled: Story = { name: "部分选中且禁用", args: { demoVariant: "indeterminate-disabled" } }
