// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.
import type { Meta, StoryObj } from '@storybook/react-vite'
import { RuntimeExample } from '../../components/RuntimeExample'
import { PreviewScope } from '../theme/PreviewScope'
import { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'
import { guokexinProject } from '../../data/projects/guokexin'
import '../../styles/index.css'
const meta = { title: 'Core/drawer', component: RuntimeExample, tags:['autodocs'], args:{id:'drawer',demoVariant:'info'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["info","form","long","nested","protected","loading"]}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:"抽屉：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。"}}} } satisfies Meta<typeof RuntimeExample>
export default meta
type Story = StoryObj<typeof meta>
export const Info: Story = { name: "查看", args: { demoVariant: "info" } }
export const Form: Story = { name: "编辑", args: { demoVariant: "form" } }
export const Long: Story = { name: "长内容滚动", args: { demoVariant: "long" } }
export const Nested: Story = { name: "嵌套选择器", args: { demoVariant: "nested" } }
export const Protected: Story = { name: "关闭方式限制", args: { demoVariant: "protected" } }
export const Loading: Story = { name: "加载保护", args: { demoVariant: "loading" } }
