// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.
import type { Meta, StoryObj } from '@storybook/react-vite'
import { RuntimeExample } from '../../components/RuntimeExample'
import { PreviewScope } from '../theme/PreviewScope'
import { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'
import { guokexinProject } from '../../data/projects/guokexin'
import '../../styles/index.css'
const meta = { title: 'Core/input', component: RuntimeExample, tags:['autodocs'], args:{id:'input',demoVariant:'default'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","filled","invalid","disabled","readonly","required","max-length","adornments"]}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:"输入框：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。"}}} } satisfies Meta<typeof RuntimeExample>
export default meta
type Story = StoryObj<typeof meta>
export const Default: Story = { name: "默认", args: { demoVariant: "default" } }
export const Filled: Story = { name: "已填写", args: { demoVariant: "filled" } }
export const Invalid: Story = { name: "错误", args: { demoVariant: "invalid" } }
export const Disabled: Story = { name: "禁用", args: { demoVariant: "disabled" } }
export const Readonly: Story = { name: "只读且可清空", args: { demoVariant: "readonly" } }
export const Required: Story = { name: "必填", args: { demoVariant: "required" } }
export const MaxLength: Story = { name: "长度限制", args: { demoVariant: "max-length" } }
export const Adornments: Story = { name: "前后缀", args: { demoVariant: "adornments" } }
