// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.
import type { Meta, StoryObj } from '@storybook/react-vite'
import { RuntimeExample } from '../../components/RuntimeExample'
import { PreviewScope } from '../theme/PreviewScope'
import { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'
import { guokexinProject } from '../../data/projects/guokexin'
import '../../styles/index.css'
const meta = { title: 'Core/search-field', component: RuntimeExample, tags:['autodocs'], args:{id:'search-field',demoVariant:'default'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","filled","disabled","invalid","readonly"]}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:"搜索框：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。"}}} } satisfies Meta<typeof RuntimeExample>
export default meta
type Story = StoryObj<typeof meta>
export const Default: Story = { name: "空值", args: { demoVariant: "default" } }
export const Filled: Story = { name: "已输入", args: { demoVariant: "filled" } }
export const Disabled: Story = { name: "禁用", args: { demoVariant: "disabled" } }
export const Invalid: Story = { name: "错误", args: { demoVariant: "invalid" } }
export const Readonly: Story = { name: "只读", args: { demoVariant: "readonly" } }
