// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.
import type { Meta, StoryObj } from '@storybook/react-vite'
import { RuntimeExample } from '../../components/RuntimeExample'
import { PreviewScope } from '../theme/PreviewScope'
import { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'
import { guokexinProject } from '../../data/projects/guokexin'
import '../../styles/index.css'
const meta = { title: 'Core/select', component: RuntimeExample, tags:['autodocs'], args:{id:'select',demoVariant:'default'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","selected","invalid","disabled","readonly","required","clearable","empty","disabled-option","long-option"]}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:"选择器：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。"}}} } satisfies Meta<typeof RuntimeExample>
export default meta
type Story = StoryObj<typeof meta>
export const Default: Story = { name: "未选择", args: { demoVariant: "default" } }
export const Selected: Story = { name: "已选择", args: { demoVariant: "selected" } }
export const Invalid: Story = { name: "错误", args: { demoVariant: "invalid" } }
export const Disabled: Story = { name: "禁用", args: { demoVariant: "disabled" } }
export const Readonly: Story = { name: "只读", args: { demoVariant: "readonly" } }
export const Required: Story = { name: "必填且配置清空", args: { demoVariant: "required" } }
export const Clearable: Story = { name: "可清空", args: { demoVariant: "clearable" } }
export const Empty: Story = { name: "空选项", args: { demoVariant: "empty" } }
export const DisabledOption: Story = { name: "含禁用选项", args: { demoVariant: "disabled-option" } }
export const LongOption: Story = { name: "长选项", args: { demoVariant: "long-option" } }
