// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.
import type { Meta, StoryObj } from '@storybook/react-vite'
import { RuntimeExample } from '../../components/RuntimeExample'
import { PreviewScope } from '../theme/PreviewScope'
import { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'
import { guokexinProject } from '../../data/projects/guokexin'
import '../../styles/index.css'
const meta = { title: 'Core/switch', component: RuntimeExample, tags:['autodocs'], args:{id:'switch',demoVariant:'default'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","checked","disabled","loading","checked-disabled"]}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:"开关：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。"}}} } satisfies Meta<typeof RuntimeExample>
export default meta
type Story = StoryObj<typeof meta>
export const Default: Story = { name: "关闭", args: { demoVariant: "default" } }
export const Checked: Story = { name: "开启", args: { demoVariant: "checked" } }
export const Disabled: Story = { name: "禁用", args: { demoVariant: "disabled" } }
export const Loading: Story = { name: "加载", args: { demoVariant: "loading" } }
export const CheckedDisabled: Story = { name: "开启且禁用", args: { demoVariant: "checked-disabled" } }
