// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.
import type { Meta, StoryObj } from '@storybook/react-vite'
import { RuntimeExample } from '../../components/RuntimeExample'
import { PreviewScope } from '../theme/PreviewScope'
import { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'
import { guokexinProject } from '../../data/projects/guokexin'
import '../../styles/index.css'
const meta = { title: 'Core/table', component: RuntimeExample, tags:['autodocs'], args:{id:'table',demoVariant:'default'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["default","secondary","pagination","grouped-header","grouped-fixed","grouped-selection","grouped-empty","grouped-loading","compact","comfortable","selection","loading","empty","no-results","sorting","paged-selection"]}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:"表格：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。"}}} } satisfies Meta<typeof RuntimeExample>
export default meta
type Story = StoryObj<typeof meta>
export const Default: Story = { name: "标准", args: { demoVariant: "default" } }
export const Secondary: Story = { name: "轻量表格", args: { demoVariant: "secondary" } }
export const Pagination: Story = { name: "表格与分页", args: { demoVariant: "pagination" } }
export const GroupedHeader: Story = { name: "多级表头", args: { demoVariant: "grouped-header" } }
export const GroupedFixed: Story = { name: "多级表头与固定列", args: { demoVariant: "grouped-fixed" } }
export const GroupedSelection: Story = { name: "多级表头与选择", args: { demoVariant: "grouped-selection" } }
export const GroupedEmpty: Story = { name: "多级表头空数据", args: { demoVariant: "grouped-empty" } }
export const GroupedLoading: Story = { name: "多级表头加载", args: { demoVariant: "grouped-loading" } }
export const Compact: Story = { name: "紧凑", args: { demoVariant: "compact" } }
export const Comfortable: Story = { name: "宽松", args: { demoVariant: "comfortable" } }
export const Selection: Story = { name: "可选择", args: { demoVariant: "selection" } }
export const Loading: Story = { name: "加载", args: { demoVariant: "loading" } }
export const Empty: Story = { name: "空数据", args: { demoVariant: "empty" } }
export const NoResults: Story = { name: "无搜索结果", args: { demoVariant: "no-results" } }
export const Sorting: Story = { name: "受控排序", args: { demoVariant: "sorting" } }
export const PagedSelection: Story = { name: "跨页选择", args: { demoVariant: "paged-selection" } }
