// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.
import type { Meta, StoryObj } from '@storybook/react-vite'
import { RuntimeExample } from '../../components/RuntimeExample'
import { PreviewScope } from '../theme/PreviewScope'
import { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'
import { guokexinProject } from '../../data/projects/guokexin'
import '../../styles/index.css'
const meta = { title: 'Core/tabs', component: RuntimeExample, tags:['autodocs'], args:{id:'tabs',demoVariant:'horizontal'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["horizontal","filled","vertical","vertical-filled","full-width","with-icons","overflow","disabled-item","disabled"]}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:"标签页：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。"}}} } satisfies Meta<typeof RuntimeExample>
export default meta
type Story = StoryObj<typeof meta>
export const Horizontal: Story = { name: "下划线", args: { demoVariant: "horizontal" } }
export const Filled: Story = { name: "填充式", args: { demoVariant: "filled" } }
export const Vertical: Story = { name: "纵向下划线", args: { demoVariant: "vertical" } }
export const VerticalFilled: Story = { name: "纵向填充", args: { demoVariant: "vertical-filled" } }
export const FullWidth: Story = { name: "等宽填充", args: { demoVariant: "full-width" } }
export const WithIcons: Story = { name: "图标与数量", args: { demoVariant: "with-icons" } }
export const Overflow: Story = { name: "溢出滚动", args: { demoVariant: "overflow" } }
export const DisabledItem: Story = { name: "含禁用项", args: { demoVariant: "disabled-item" } }
export const Disabled: Story = { name: "全部禁用", args: { demoVariant: "disabled" } }
