// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.
import type { Meta, StoryObj } from '@storybook/react-vite'
import { RuntimeExample } from '../../components/RuntimeExample'
import { PreviewScope } from '../theme/PreviewScope'
import { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'
import { guokexinProject } from '../../data/projects/guokexin'
import '../../styles/index.css'
const meta = { title: 'Core/toast', component: RuntimeExample, tags:['autodocs'], args:{id:'toast',demoVariant:'info'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:["info","success","error","restart","persistent"]}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:"轻提示：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。"}}} } satisfies Meta<typeof RuntimeExample>
export default meta
type Story = StoryObj<typeof meta>
export const Info: Story = { name: "信息", args: { demoVariant: "info" } }
export const Success: Story = { name: "成功", args: { demoVariant: "success" } }
export const Error: Story = { name: "错误", args: { demoVariant: "error" } }
export const Restart: Story = { name: "关闭后重开", args: { demoVariant: "restart" } }
export const Persistent: Story = { name: "持续显示", args: { demoVariant: "persistent" } }
