// @vitest-environment jsdom
import { cleanup, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeAll, expect, it, vi } from 'vitest'
import { ResourceWorkflow } from './ResourceWorkflow'
beforeAll(()=>{vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});window.matchMedia=vi.fn().mockReturnValue({matches:false,addEventListener(){},removeEventListener(){}})})
afterEach(cleanup)
it('筛选、查看、编辑失败重试、返回后保留筛选并更新原行',async()=>{
 const user=userEvent.setup();render(<ResourceWorkflow/>);await user.type(screen.getByRole('textbox',{name:'搜索资源'}),'政策')
 await user.click(screen.getByRole('button',{name:'查看资源'}));expect(screen.getByText('政策与研究资料的统一管理入口。')).toBeTruthy()
 await user.click(screen.getByRole('button',{name:'编辑当前资源'}));const name=screen.getByRole('textbox',{name:'资源名称'});await user.clear(name);await user.type(name,'政策数据库更新')
 await user.click(screen.getByRole('checkbox',{name:'模拟一次提交失败'}));await user.click(screen.getByRole('button',{name:'保存资源'}));expect(await screen.findByText('本次提交失败，输入已保留。请重试。',{selector:'.owned-form-feedback span'})).toBeTruthy()
 expect((name as HTMLInputElement).value).toBe('政策数据库更新');await user.click(screen.getByRole('button',{name:'保存资源'}));expect(await screen.findByRole('cell',{name:'政策数据库更新'})).toBeTruthy();expect((screen.getByRole('textbox',{name:'搜索资源'}) as HTMLInputElement).value).toBe('政策')
})
it('未保存关闭支持继续编辑或明确放弃',async()=>{
 const user=userEvent.setup();render(<ResourceWorkflow drawerEdit/>);await user.click(screen.getAllByRole('button',{name:'编辑资源'})[0]);const input=screen.getByRole('textbox',{name:'资源名称'});await user.type(input,'修改');await user.click(screen.getByRole('button',{name:'取消编辑'}));const dialog=screen.getByRole('dialog',{name:'放弃未保存的修改？'});await user.click(within(dialog).getByRole('button',{name:'继续编辑'}));expect((input as HTMLInputElement).value).toContain('修改');await user.click(screen.getByRole('button',{name:'取消编辑'}));await user.click(screen.getByRole('button',{name:'放弃修改'}));expect(screen.queryByRole('dialog')).toBeNull()
})
it('只读不允许修改；权限不足不展示受限数据',()=>{
 const {rerender}=render(<ResourceWorkflow scenario="readonly"/>);expect((screen.getByRole('button',{name:'新增资源'}) as HTMLButtonElement).disabled).toBe(true)
 rerender(<ResourceWorkflow key="permission" scenario="permission"/>);expect(screen.queryByRole('table')).toBeNull();expect(screen.getByText('当前示例无查看权限')).toBeTruthy()
})
it('空数据、无结果和读取失败提供可执行恢复路径',async()=>{
 const user=userEvent.setup();const {rerender}=render(<ResourceWorkflow scenario="no-results"/>);expect(screen.getByText('没有匹配资源')).toBeTruthy();await user.click(screen.getByRole('button',{name:'清除筛选'}));expect(screen.getByRole('cell',{name:'政策数据库'})).toBeTruthy()
 rerender(<ResourceWorkflow key="error" scenario="error"/>);await user.click(screen.getByRole('button',{name:'重试加载'}));expect(screen.getByRole('table')).toBeTruthy()
})
it('独立取用未知模板或模式不会静默回退成另一页面',async()=>{
 const {TemplateExample,PatternExample}=await import('./catalog');const {rerender}=render(<TemplateExample templateId="missing"/>);expect(screen.getByText('模板不可用')).toBeTruthy();expect(screen.queryByRole('table')).toBeNull();rerender(<PatternExample patternId="missing"/>);expect(screen.getByText('模式不可用')).toBeTruthy()
})

it('高级筛选先编辑草稿，取消不影响列表，应用后才筛选',async()=>{
 const user=userEvent.setup();render(<ResourceWorkflow advanced/> )
 await user.click(screen.getByRole('button',{name:'高级筛选'}));await user.click(screen.getByRole('button',{name:/资源类型条件/}));await user.click(screen.getByRole('option',{name:'配置项'}));await user.click(screen.getByRole('button',{name:'取消筛选'}))
 expect(screen.getByRole('cell',{name:'政策数据库'})).toBeTruthy()
 await user.click(screen.getByRole('button',{name:'高级筛选'}));await user.click(screen.getByRole('button',{name:/资源类型条件/}));await user.click(screen.getByRole('option',{name:'配置项'}));await user.click(screen.getByRole('button',{name:'应用筛选'}))
 expect(screen.queryByRole('cell',{name:'政策数据库'})).toBeNull();expect(screen.getByRole('cell',{name:'专题配置'})).toBeTruthy()
})
it('长内容表单未编辑时不误报未保存修改',async()=>{
 const user=userEvent.setup();render(<ResourceWorkflow initialView="edit" scenario="long"/>);expect(document.querySelector('.resource-workflow')?.getAttribute('data-unsaved')).toBeNull();await user.click(screen.getByRole('button',{name:'取消编辑'}));expect(screen.queryByRole('dialog')).toBeNull()
})
it('同一批次重复提交只创建一条资源',async()=>{
 const {fireEvent,act}=await import('@testing-library/react');const user=userEvent.setup();render(<ResourceWorkflow/>);await user.click(screen.getByRole('button',{name:'新增资源'}));await user.type(screen.getByRole('textbox',{name:'资源名称'}),'重复提交验证')
 const form=screen.getByRole('form',{name:'编辑资源表单'});act(()=>{fireEvent.submit(form);fireEvent.submit(form)})
 expect(await screen.findByRole('cell',{name:'重复提交验证'})).toBeTruthy();expect(screen.getAllByRole('cell',{name:'重复提交验证'})).toHaveLength(1)
})
it('编辑时的导航和浏览器返回均可取消',async()=>{
 const {fireEvent}=await import('@testing-library/react');const user=userEvent.setup();window.history.replaceState({idx:2},'','/editing');const confirm=vi.spyOn(window,'confirm').mockReturnValue(false),go=vi.spyOn(window.history,'go').mockImplementation(()=>{})
 const {unmount}=render(<><a href="/other">其他页面</a><ResourceWorkflow initialView="edit"/></>);await user.type(screen.getByRole('textbox',{name:'资源名称'}),'修改')
 expect(fireEvent.click(screen.getByRole('link',{name:'其他页面'}))).toBe(false)
 window.dispatchEvent(new PopStateEvent('popstate',{state:{idx:1}}));expect(go).toHaveBeenCalledWith(1);expect(confirm).toHaveBeenCalledTimes(2)
 unmount();confirm.mockRestore();go.mockRestore();window.history.replaceState({},'','/')
})

it('第二页切换每页条数后回到首页，同步列表、页数并保留筛选',async()=>{
 const user=userEvent.setup();render(<ResourceWorkflow/> )
 await user.click(screen.getByRole('button',{name:'第 2 页'}))
 expect(screen.getByRole('cell',{name:'历史映射'})).toBeTruthy()
 expect(screen.queryByRole('cell',{name:'政策数据库'})).toBeNull()
 await user.click(screen.getByRole('button',{name:/每页条数/}))
 expect(screen.getAllByRole('option').map(option=>option.textContent)).toEqual(['3条','10条','20条','50条'])
 await user.click(screen.getByRole('option',{name:'10条'}))
 expect(screen.getAllByRole('row')).toHaveLength(5)
 expect(screen.getByText('共 4 条')).toBeTruthy()
 expect((screen.getByRole('button',{name:'下一页'}) as HTMLButtonElement).disabled).toBe(true)
 await user.click(screen.getByRole('button',{name:/每页条数/}));await user.click(screen.getByRole('option',{name:'3条'}))
 expect(screen.getAllByRole('row')).toHaveLength(4)
 expect(screen.getByText('共 4 条')).toBeTruthy()
 await user.type(screen.getByRole('textbox',{name:'搜索资源'}),'配置')
 await user.click(screen.getByRole('button',{name:/每页条数/}));await user.click(screen.getByRole('option',{name:'20条'}))
 expect((screen.getByRole('textbox',{name:'搜索资源'}) as HTMLInputElement).value).toBe('配置')
 expect(screen.getByRole('cell',{name:'专题配置'})).toBeTruthy()
 expect(screen.getByText('共 1 条')).toBeTruthy()
})
it('页容量下拉继承项目预览主题，支持键盘选择；固定容量不显示可操作的假入口',async()=>{
 const {PreviewScope}=await import('../design-system/theme/PreviewScope')
 const {DSPagination}=await import('../runtime')
 const user=userEvent.setup()
 const {unmount}=render(<PreviewScope vars={{'--brand-primary':'#165DFF'} as React.CSSProperties} inspectionId="pagination-test"><ResourceWorkflow/></PreviewScope>)
 await user.click(screen.getByRole('button',{name:/每页条数/}))
 const popover=screen.getByRole('listbox',{name:/每页条数/}).closest('.owned-select__popover') as HTMLElement
 expect(popover.style.getPropertyValue('--brand-primary')).toBe('#165DFF')
 expect(popover.dataset.previewOwner).toBe('pagination-test')
 await user.keyboard('{ArrowDown}{Enter}')
 expect(screen.getByText('共 4 条')).toBeTruthy()
 unmount();render(<DSPagination page={1} pageSize={3} pageSizeOptions={[3]} total={4} onPageChange={()=>{}}/>)
 expect((screen.getByRole('button',{name:/每页条数/}) as HTMLButtonElement).disabled).toBe(true)
})

it('全选仅作用于当前页，跨页结果必须显式选择；批量条与新增操作分开',async()=>{
 const user=userEvent.setup();render(<ResourceWorkflow bulk/>)
 expect(screen.queryByRole('region',{name:'批量操作'})).toBeNull()
 await user.click(screen.getByRole('checkbox',{name:'选择行 政策数据库'}))
 expect((screen.getByRole('checkbox',{name:'全选当前页'}) as HTMLInputElement).indeterminate).toBe(true)
 await user.click(screen.getByRole('checkbox',{name:'全选当前页'}))
 const bar=screen.getByRole('region',{name:'批量操作'})
 expect(bar.textContent).toContain('已选择 3 项')
 expect(bar.contains(screen.getByRole('button',{name:'新增资源'}))).toBe(false)
 await user.click(screen.getByRole('button',{name:'选择全部 4 项'}))
 expect(bar.textContent).toContain('已选择 4 项')
 await user.click(screen.getByRole('button',{name:'第 2 页'}))
 expect(bar.textContent).toContain('含其他页 3 项')
 expect((screen.getByRole('checkbox',{name:'全选当前页'}) as HTMLInputElement).checked).toBe(true)
 await user.click(screen.getByRole('checkbox',{name:'全选当前页'}))
 expect(bar.textContent).toContain('已选择 3 项')
 await user.type(screen.getByRole('textbox',{name:'搜索资源'}),'政策')
 expect(screen.queryByRole('region',{name:'批量操作'})).toBeNull()
 expect((screen.getByRole('checkbox',{name:'全选当前页'}) as HTMLInputElement).checked).toBe(false)
})
it('普通列表点击行不会发生隐形选择；空、加载和只读使用明确的选择与分页状态',async()=>{
 const user=userEvent.setup();const {rerender}=render(<ResourceWorkflow/>)
 await user.click(screen.getByRole('cell',{name:'政策数据库'}))
 expect(document.querySelector('.ds-table__row.is-selected')).toBeNull()
 rerender(<ResourceWorkflow key="empty" scenario="empty" bulk/>)
 expect((screen.getByRole('checkbox',{name:'全选当前页'}) as HTMLInputElement).disabled).toBe(true)
 expect(screen.queryByRole('navigation',{name:'分页'})).toBeNull()
 rerender(<ResourceWorkflow key="loading" scenario="table-loading" bulk/>)
 expect((screen.getByRole('checkbox',{name:'全选当前页'}) as HTMLInputElement).disabled).toBe(true)
 expect((screen.getByRole('button',{name:'下一页'}) as HTMLButtonElement).disabled).toBe(true)
 rerender(<ResourceWorkflow key="readonly" scenario="readonly" bulk initialSelection="all"/>)
 expect(screen.queryByRole('checkbox',{name:'全选当前页'})).toBeNull()
 expect(screen.queryByRole('region',{name:'批量操作'})).toBeNull()
 expect(document.querySelector('.ds-table__row.is-selected')).toBeNull()
})
