import {writeFileSync,mkdirSync} from 'node:fs'
import {AI_COMPONENTS} from '../src/data/ai-components'
mkdirSync('src/design-system/stories',{recursive:true})
for(const item of AI_COMPONENTS){
 const stories=item.variants.map(([id,label])=>`export const ${id.split('-').map(word=>word[0].toUpperCase()+word.slice(1)).join('')}: Story = { name:${JSON.stringify(label)},args:{demoVariant:${JSON.stringify(id)}} }`).join('\n')
 writeFileSync(`src/design-system/stories/ai-${item.id}.stories.tsx`,`// Generated by scripts/generate-ai-stories.ts.\nimport type {Meta,StoryObj} from '@storybook/react-vite'\nimport {RuntimeExample} from '../../components/RuntimeExample'\nimport {PreviewScope} from '../theme/PreviewScope'\nimport {baselineThemeSettings,projectPreviewVariables} from '../../services/project-theme'\nimport '../../styles/index.css'\nconst meta={title:'AI/${item.id}',component:RuntimeExample,tags:['autodocs'],args:{id:'${item.id}',demoVariant:'default'},argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:${JSON.stringify(item.variants.map(v=>v[0]))}}},decorators:[Story=><PreviewScope vars={projectPreviewVariables(baselineThemeSettings)}><div style={{width:'min(760px,90vw)',padding:24}}><Story/></div></PreviewScope>]} satisfies Meta<typeof RuntimeExample>\nexport default meta\ntype Story=StoryObj<typeof meta>\n${stories}\n`)
}
console.log(`Generated ${AI_COMPONENTS.length} AI stories`)
