import { mkdirSync, writeFileSync } from 'node:fs'
import { CORE_COMPONENT_IDS } from '../src/data/core-quality'
import { componentDemoVariants } from '../src/design-system/component-demo-variants'
import { componentDisplayName } from '../src/design-system/component-catalog'
const directory=new URL('../src/design-system/stories/',import.meta.url)
mkdirSync(directory,{recursive:true})
for(const id of CORE_COMPONENT_IDS){
 const variants=componentDemoVariants(id)
 const extra=id==='button'?`\nexport const Disabled: Story = {name:'禁用',args:{disabled:true}}\nexport const Loading: Story = {name:'加载',args:{buttonLoading:true}}` : ''
 const stories=variants.map(item=>`export const ${item.id.replace(/(^|-)(\w)/g,(_,p,c)=>c.toUpperCase())}: Story = { name: ${JSON.stringify(item.label)}, args: { demoVariant: ${JSON.stringify(item.id)}${id==='button'?`, buttonVariant: ${JSON.stringify(['primary','secondary','tertiary'].includes(item.id)?item.id:'primary')}, buttonSemantic: ${JSON.stringify(item.id==='danger'?'danger':'default')}`:''} } }`).join('\n')
 writeFileSync(new URL(`${id}.stories.tsx`,directory),`// Generated by scripts/generate-core-stories.ts. Uses the same real controls as component details.\nimport type { Meta, StoryObj } from '@storybook/react-vite'\nimport { RuntimeExample } from '../../components/RuntimeExample'\nimport { PreviewScope } from '../theme/PreviewScope'\nimport { defaultProjectTheme, projectPreviewVariables } from '../../services/project-theme'\nimport { guokexinProject } from '../../data/projects/guokexin'\nimport '../../styles/index.css'\nconst meta = { title: 'Core/${id}', component: RuntimeExample, tags:['autodocs'], args:{id:'${id}',demoVariant:'${variants[0].id}'}, argTypes:{id:{table:{disable:true}},demoVariant:{control:'select',options:${JSON.stringify(variants.map(v=>v.id))}}}, decorators:[Story=><PreviewScope vars={projectPreviewVariables(defaultProjectTheme(guokexinProject))}><div style={{width:'min(880px,90vw)',padding:24}}><Story/></div></PreviewScope>], parameters:{docs:{description:{component:${JSON.stringify(`${componentDisplayName(id)}：真实 DS 控件。交互、禁用和异常示例与组件详情同源；状态是否适用以组件 API 为准。`)}}}} } satisfies Meta<typeof RuntimeExample>\nexport default meta\ntype Story = StoryObj<typeof meta>\n${stories}${extra}\n`)
}
console.log(`Generated core stories for ${CORE_COMPONENT_IDS.length} components.`)
