import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { resolveProjectTheme } from '../src/services/theme-resolver'
import { semanticTokens } from '../src/data/global/semantic-tokens'
import { buttonRecipeTokens } from '../src/data/components/button-recipe-tokens'
import { guokexinProject } from '../src/data/projects/guokexin'
import { runtimeThemeAliases } from '../src/design-system/theme/runtimeThemeAliases'

const projectRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
const outputPath = resolve(projectRoot, 'src/design-system/tokens.css')
const allTokens = [...semanticTokens, ...buttonRecipeTokens]
const ids = new Set<string>()

for (const token of allTokens) {
  if (ids.has(token.id)) throw new Error(`重复 Token ID：${token.id}`)
  ids.add(token.id)
}

for (const tokenId of Object.keys(guokexinProject.tokenOverrides)) {
  if (!ids.has(tokenId)) throw new Error(`项目覆盖引用了不存在的 Token：${tokenId}`)
}

const baselineDeclarations = allTokens
  .map((token) => `  --${token.id}: ${token.defaultValue};`)
  .join('\n')

const projectValues = resolveProjectTheme(guokexinProject).values
const projectDeclarations = allTokens
  .map((token) => {
    const value = projectValues[token.id] ?? token.defaultValue
    return `  --${token.id}: ${value};`
  })
  .join('\n')

const runtimeAliasDeclarations = Object.entries(runtimeThemeAliases)
  .map(([name, value]) => `  ${name}: ${value};`)
  .join('\n')

const css = `/*
 * AUTO-GENERATED by scripts/generate-token-css.ts.
 * Sources: semantic-tokens.ts + projects/guokexin.
 * Do not edit this file directly.
 */
:root,
.theme-baseline {
${baselineDeclarations}
${runtimeAliasDeclarations}
}

.theme-guokexin {
${projectDeclarations}
${runtimeAliasDeclarations}
}
`

writeFileSync(outputPath, css)
console.log(`Generated ${allTokens.length} source CSS Variables plus ${Object.keys(runtimeThemeAliases).length} Runtime aliases (${semanticTokens.length} global + ${buttonRecipeTokens.length} component) → ${outputPath}`)
