import { ScopedPopover as Popover } from '../../theme/PreviewScope'
import { Calendar, RangeCalendar, CalendarGrid, CalendarCell, Button, Heading, DateField, DateInput, DateSegment, TimeField, DatePicker, DateRangePicker, Group, Label, Dialog, FieldError } from 'react-aria-components'
import type { ComponentProps } from 'react'
import { DSIcon } from '../../../runtime/vendor/runtime.js'
import '../AdvancedFields/Fields.css'
import './DateTime.css'
function CalendarHeader(){return <header><Button slot="previous" aria-label="上个月"><DSIcon name="chevron-left" size="sm" decorative /></Button><Heading /><Button slot="next" aria-label="下个月"><DSIcon name="chevron-right" size="sm" decorative /></Button></header>}
export type DSCalendarProps=Omit<ComponentProps<typeof Calendar>,'children'|'className'>
export function DSCalendar(props:DSCalendarProps){return <Calendar {...props} className="owned-calendar"><CalendarHeader /><CalendarGrid>{date=><CalendarCell date={date} />}</CalendarGrid></Calendar>}
export function DSRangeCalendar(props:Omit<ComponentProps<typeof RangeCalendar>,'children'|'className'>){return <RangeCalendar {...props} className="owned-calendar"><CalendarHeader /><CalendarGrid>{date=><CalendarCell date={date} />}</CalendarGrid></RangeCalendar>}
function Segments(){return <DateInput className="owned-date-input">{segment=><DateSegment segment={segment} />}</DateInput>}
export function DSDateField({label,...props}:Omit<ComponentProps<typeof DateField>,'children'|'className'>&{label:string}){return <DateField {...props} className="owned-date-field owned-field-stack"><Label className="owned-field-label">{label}</Label><Segments /><FieldError className="owned-field-error" /></DateField>}
export function DSTimeField({label,...props}:Omit<ComponentProps<typeof TimeField>,'children'|'className'>&{label:string}){return <TimeField {...props} className="owned-date-field owned-field-stack"><Label className="owned-field-label">{label}</Label><Segments /><FieldError className="owned-field-error" /></TimeField>}
export function DSDatePicker({label,...props}:Omit<ComponentProps<typeof DatePicker>,'children'|'className'>&{label:string}){return <DatePicker {...props} className="owned-date-picker owned-field-stack"><Label className="owned-field-label">{label}</Label><Group className="owned-control-row owned-date-picker__control"><Segments /><Button aria-label={`选择${label}`}><DSIcon name="calendar" size="sm" decorative /></Button></Group><FieldError className="owned-field-error" /><Popover className="owned-select__popover owned-calendar-popover"><Dialog><DSCalendar /></Dialog></Popover></DatePicker>}
export function DSDateRangePicker({label,...props}:Omit<ComponentProps<typeof DateRangePicker>,'children'|'className'>&{label:string}){return <DateRangePicker {...props} className="owned-date-range-picker owned-field-stack"><Label className="owned-field-label">{label}</Label><Group className="owned-control-row owned-date-picker__control"><DateInput slot="start" className="owned-date-input">{segment=><DateSegment segment={segment}/>}</DateInput><span className="owned-date-range-picker__separator" aria-hidden="true">至</span><DateInput slot="end" className="owned-date-input">{segment=><DateSegment segment={segment}/>}</DateInput><Button aria-label={`选择${label}`}><DSIcon name="calendar-days" size="sm" decorative /></Button></Group><FieldError className="owned-field-error" /><Popover className="owned-select__popover owned-calendar-popover"><Dialog><DSRangeCalendar /></Dialog></Popover></DateRangePicker>}
